services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI= mongodb://mongo:27017/todox
      - JWT_SECRET= toi_la_18_05
      - CLIENT_URL= http://localhost:5173
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes:
  mongo-data:
